services:
  mongodb:
    image: mongo:latest
    ports:
    - 27018:27017
    volumes:
    - mongodb_data_container:/data/db

volumes:
    mongodb_data_container:
    images_data:
        external: false
